blank_issues_enabled: false
contact_links:
  - name: 🔗 Submit an issue / feature request
    url: https://github.com/umbraco/Umbraco.Commerce.Issues/issues/new/choose
    about: Please submit all issues / feature requests related to this project on the central Umbraco Commerce issue tracker here.
